_wandb:
    value:
        cli_version: 0.21.3
        e:
            y9pkbx370dkqx9gh72fz5ybt3nsape2q:
                codePath: test_wandb_connection.py
                codePathLocal: test_wandb_connection.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "158271492096"
                        used: "82793533440"
                email: benc6116@gmail.com
                executable: /home/benc6116/miniconda/bin/python
                git:
                    commit: ef138d7c6ca4607d9a435cc8725ca9dc27d4b9bc
                    remote: git@github.com:benc61116/NLP.git
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-0ca39d40-f72c-ff40-394a-33b1dbd31970
                host: gnn-l4-01
                memory:
                    total: "33671041024"
                os: Linux-5.10.0-35-cloud-amd64-x86_64-with-glibc2.31
                program: /home/benc6116/workspace/NLP/test_wandb_connection.py
                python: CPython 3.13.5
                root: /home/benc6116/workspace/NLP
                startedAt: "2025-09-21T19:04:39.966837Z"
                writerId: y9pkbx370dkqx9gh72fz5ybt3nsape2q
        m: []
        python_version: 3.13.5
        t:
            "3":
                - 2
                - 13
                - 15
            "4": 3.13.5
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
batch_size:
    value: 32
learning_rate:
    value: 0.001
model:
    value: test_model
test_parameter:
    value: connection_test
