best_hyperparameters:
  learning_rate: 3.782108111851264e-05
  num_train_epochs: 4
  per_device_train_batch_size: 1
  warmup_ratio: 0.24004003822996867
  weight_decay: 0.07778254670477941
expected_performance: 0.84
method: full_finetune
optimization_summary:
  n_completed: 10
  n_pruned: 0
  n_trials: 10
task: mrpc
