optimal_hyperparameters:
  full_finetune:
    expected_performance: 0.84
    hyperparameters:
      learning_rate: 3.782108111851264e-05
      num_train_epochs: 4
      per_device_train_batch_size: 1
      warmup_ratio: 0.24004003822996867
      weight_decay: 0.07778254670477941
    optimization_summary:
      n_completed: 10
      n_pruned: 0
      n_trials: 10
  lora:
    expected_performance: 0.78
    hyperparameters:
      learning_rate: 0.00038269770508019034
      lora_alpha: 16
      lora_dropout: 0.04626805922039857
      lora_r: 8
      num_train_epochs: 3
      per_device_train_batch_size: 8
      warmup_ratio: 0.1139705119739972
      weight_decay: 0.0337605113187364
    optimization_summary:
      n_completed: 10
      n_pruned: 0
      n_trials: 10
optimization_efficiency: 67% faster
optimization_method: optuna_tpe_optimized
task: mrpc
total_trials: 20
trials_per_method: 10
