best_hyperparameters:
  learning_rate: 0.0003823496201652767
  lora_alpha: 16
  lora_dropout: 0.286899218846719
  lora_r: 8
  num_train_epochs: 2
  per_device_train_batch_size: 16
  warmup_ratio: 0.09385407381922162
  weight_decay: 0.010328085443767267
expected_performance: 0.62
method: lora
optimization_summary:
  n_completed: 10
  n_pruned: 0
  n_trials: 10
task: rte
