best_hyperparameters:
  learning_rate: 1.7018418817029176e-05
  num_train_epochs: 4
  per_device_train_batch_size: 1
  warmup_ratio: 0.23555278841790406
  weight_decay: 0.019967378215835975
expected_performance: 0.8
method: full_finetune
optimization_summary:
  n_completed: 10
  n_pruned: 0
  n_trials: 10
task: rte
