best_hyperparameters:
  learning_rate: 9.662725253044474e-06
  num_train_epochs: 4
  per_device_train_batch_size: 1
  warmup_ratio: 0.0854944020516992
  weight_decay: 0.0176370230835036
expected_performance: 0.68
method: full_finetune
optimization_summary:
  n_completed: 10
  n_pruned: 0
  n_trials: 10
task: rte
