best_hyperparameters:
  learning_rate: 0.00040114258852550313
  lora_alpha: 32
  lora_dropout: 0.22670115279994313
  lora_r: 8
  num_train_epochs: 3
  per_device_train_batch_size: 8
  warmup_ratio: 0.11198847499353282
  weight_decay: 0.025598711056396842
expected_performance: 0.64
method: lora
optimization_summary:
  n_completed: 10
  n_pruned: 0
  n_trials: 10
task: rte
