best_hyperparameters:
  learning_rate: 3.781100245923437e-05
  num_train_epochs: 4
  per_device_train_batch_size: 2
  warmup_ratio: 0.1753877569535983
  weight_decay: 0.003219640818008801
expected_performance: 0.5566666666666666
method: full_finetune
optimization_summary:
  n_completed: 15
  n_failed: 0
  n_trials: 15
  success_rate: 100.0
  total_time_seconds: 11052.53223323822
optimization_type: manual_single_trial_sweep
task: squad_v2
