best_hyperparameters:
  learning_rate: 3.971084710792477e-05
  num_train_epochs: 2
  per_device_train_batch_size: 1
  warmup_ratio: 0.013935123815999317
  weight_decay: 0.06075448519014384
expected_performance: 0.18
method: full_finetune
optimization_summary:
  n_completed: 17
  n_pruned: 0
  n_trials: 18
task: squad_v2
