best_hyperparameters:
  learning_rate: 2.2965667369190676e-05
  num_train_epochs: 3
  per_device_train_batch_size: 1
  warmup_ratio: 0.22532174554982123
  weight_decay: 0.041129357499572375
expected_performance: 0.18
method: full_finetune
optimization_summary:
  n_completed: 20
  n_pruned: 0
  n_trials: 20
task: squad_v2
