best_hyperparameters:
  learning_rate: 1.0253509690168497e-05
  num_train_epochs: 2
  per_device_train_batch_size: 4
  warmup_ratio: 0.04680559213273095
  weight_decay: 0.015599452033620266
expected_performance: 0.0
method: full_finetune
optimization_summary:
  n_completed: 30
  n_pruned: 0
  n_trials: 30
task: squad_v2
