optimal_hyperparameters:
  full_finetune:
    expected_performance: 0.5566666666666666
    hyperparameters:
      learning_rate: 3.781100245923437e-05
      num_train_epochs: 4
      per_device_train_batch_size: 2
      warmup_ratio: 0.1753877569535983
      weight_decay: 0.003219640818008801
    optimization_summary:
      n_completed: 15
      n_failed: 0
      n_trials: 15
      success_rate: 100.0
      total_time_seconds: 11052.53223323822
  lora:
    expected_performance: 0.5666666666666667
    hyperparameters:
      learning_rate: 0.00024371003900392795
      lora_alpha: 64
      lora_dropout: 0.2726772085613049
      lora_r: 8
      num_train_epochs: 3
      per_device_train_batch_size: 4
      warmup_ratio: 0.04371157655588848
      weight_decay: 0.07764226130886216
    optimization_summary:
      n_completed: 15
      n_failed: 0
      n_trials: 15
      success_rate: 100.0
      total_time_seconds: 7675.124737262726
optimization_efficiency: 33% faster
optimization_method: optuna_tpe_optimized
task: squad_v2
total_trials: 40
trials_per_method: 20
