best_hyperparameters:
  learning_rate: 5.5627080403346613e-05
  num_train_epochs: 4
  per_device_train_batch_size: 1
  warmup_ratio: 0.1694315312960467
  weight_decay: 0.08197129194236585
expected_performance: 0.92
method: full_finetune
optimization_summary:
  n_completed: 10
  n_pruned: 0
  n_trials: 10
task: sst2
