best_hyperparameters:
  learning_rate: 1.6774962151753295e-05
  num_train_epochs: 2
  per_device_train_batch_size: 1
  warmup_ratio: 0.0791031802824938
  weight_decay: 0.0863604797174436
expected_performance: 0.0
method: full_finetune
optimization_summary:
  n_completed: 1
  n_pruned: 0
  n_trials: 1
task: squad_v2
