best_hyperparameters:
  learning_rate: 3.770366746308486e-06
  num_train_epochs: 2
  per_device_train_batch_size: 1
  warmup_ratio: 0.18379468474842162
  weight_decay: 0.02633138019808441
expected_performance: 0.0
method: full_finetune
optimization_summary:
  n_completed: 1
  n_pruned: 0
  n_trials: 1
task: squad_v2
