best_hyperparameters:
  learning_rate: 1.0444906587531284e-06
  num_train_epochs: 4
  per_device_train_batch_size: 1
  warmup_ratio: 0.14863116732659046
  weight_decay: 0.07599919885898447
expected_performance: 0.0
method: full_finetune
optimization_summary:
  n_completed: 1
  n_pruned: 0
  n_trials: 1
task: squad_v2
