best_hyperparameters:
  learning_rate: 0.0003246004468991884
  num_train_epochs: 3
  per_device_train_batch_size: 1
  warmup_ratio: 0.26150003681232825
  weight_decay: 0.0017157519061255845
expected_performance: 0.0
method: full_finetune
optimization_summary:
  n_completed: 1
  n_pruned: 0
  n_trials: 1
task: squad_v2
